### ISSUE TITLE
Fix Vite Plugin Lint package

### ISSUE THREAD

**Issue by murimessias** [fdaciuk/boilerplate-vite-react#14]
After cloning the project and running `yarn install` or `yarn update-deps`, the installation failed due to the `vite-plugin-lint` package. This prevents users from using the boilerplate without removing the package.

<img width="939" alt="image" src="https://github.com/fdaciuk/boilerplate-vite-react/assets/58787878/d14bcd6b-d207-43ea-bb2d-91743b082966">

**Comment by fdaciuk** [comment]
Good catch @murimessias! Let's check that out =)

**Comment by vinibispo** [comment]
I did a pull request fixing this

**Comment by fdaciuk** [comment]
Actually, I don't really know why this plugin is there 🤔 
Thanks @vinibispo!
